---
name: Build

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: timmo001/workflows/.github/workflows/ha-card-build.yml@e0caff057b9334455c7826e8d2c983e952981535 # master
