---
name: Build

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: timmo001/workflows/.github/workflows/ha-card-build.yml@3ba245be0bc187b911a790475801cd7934dbdf1d # master
