---
name: Release

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: timmo001/workflows/.github/workflows/ha-card-release.yml@e77c830cdc5cef3691f9840d07b74d00f4925ec3 # master
    permissions:
      contents: write
