---
name: Release

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: timmo001/workflows/.github/workflows/ha-card-release.yml@e0caff057b9334455c7826e8d2c983e952981535 # master
    permissions:
      contents: write
