---
name: Release

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: timmo001/workflows/.github/workflows/ha-card-release.yml@bc424f94da51b00a8dc3d2e5a0875b7b5cc789ae # master
    permissions:
      contents: write
