---
name: Renovate automerge

# yamllint disable-line rule:truthy
on:
  pull_request_target: {}

jobs:
  automerge:
    uses: timmo001/workflows/.github/workflows/renovate-automerge.yml@81ebf161dcea7a74711d651dc24b98f6f72614ad # master
    permissions:
      pull-requests: write
      contents: write
