---
name: HACS Validate

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate:
    uses: timmo001/workflows/.github/workflows/ha-card-validate.yml@81ebf161dcea7a74711d651dc24b98f6f72614ad # master
